version: '3'
services:
   pi_flood_workeri_fmcalc:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile.PiFloodWorker
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     - OASIS_MODEL_SUPPLIER_ID=OasisLMF
     - OASIS_MODEL_ID=PiFlood_fmcalc
     - OASIS_MODEL_VERSION_ID=0.0.1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - OASIS_KEEP_RUN_DIR=True
     - OASIS_FMPY=False
    volumes:
     - ./keys_data:/var/oasis/keys_data
     - ./model_data:/var/oasis/model_data
     - /docker-shared-fs:/shared-fs:rw

   pi_flood_worker_fmpy:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile.PiFloodWorker
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     - OASIS_MODEL_SUPPLIER_ID=OasisLMF
     - OASIS_MODEL_ID=PiFlood_fmpy
     - OASIS_MODEL_VERSION_ID=0.0.1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - OASIS_KEEP_RUN_DIR=True
     - OASIS_FMPY=True
    volumes:
     - ./keys_data:/var/oasis/keys_data
     - ./model_data:/var/oasis/model_data
     - /docker-shared-fs:/shared-fs:rw

